In [1]:
'''
    We start with one simple array with the tallest PLS from each layer (that's all you need).
    Note that each height is inside an individual array, that's because we'll append inside each
    one of them the incidence, use and availability of light.
    
    The main point it how to get to this array.
    That's what you need to do at your Fortran code.
'''

# The mains array, with the tallest PLS height of each layer.
pls_arr = [[34.0000000], [29.1428585], [24.2857151], [19.4285717], [14.5714283], [9.71428585], [4.85714293]]

# llw_pls stands for "last layer with PLS" and it's an index.
# It's initialized with 0, as the first element of 'pls_arr' must have a height setted.
llw_pls = 0

# Iterate through all elements from pls_arr.
for pls in range(len(pls_arr)):
    
    # If it's the first one, just set the light incidence as 100%.
    if pls == 0:
        light_incidence = 100
        
    # If it's not the first one, we must check if it has a PLS.
    else:
        
        # If it has...
        if len(pls_arr[pls]) > 0:
            
            # From the PLS array, we get the last layer with PLS,
            # and set the index 3 as 'light_incidence'.
            # This may not make sense now, but keep reading the code comments.
            light_incidence = pls_arr[llw_pls][3]
            
            # And set this PLS as the 'llw_pls' (because it has a PLS, of course).
            llw_pls = pls
        
        # If it hasn't, continue the loop with the next 'pls_arr' element.
        else:
            continue
    
    # Now that we have the 'light_incidence' value, we can calculate light used and available values.
    light_used = light_incidence * 0.2
    light_available = light_incidence - light_used
    
    # And finally, we append to the PLS array the light values calculated.
    pls_arr[pls].append(light_incidence)
    pls_arr[pls].append(light_used)
    pls_arr[pls].append(light_available)
    # If you think in the first iteration, the array with the height of the tallest PLS is now like:
    # [[34.0000000, 100, 20, 80], [aray_for_the_second_iteration], ...]
    # And that's why when you set 'light_incidence' as 'pls_arr[llw_pls][3]', you get
    # the value of light available from the last layer with PLS:
    # pls (0)    | light_incidence (1) | light_used (2) | light_available (3) 
    # 34.0000000 | 100                 | 20             | 80

In [2]:
from pandas import DataFrame

DataFrame(pls_arr, columns = ["pls", "light_incidence", "light_used", "light_available"])

         pls  light_incidence  light_used  light_available
0  34.000000         100.0000    20.00000         80.00000
1  29.142858          80.0000    16.00000         64.00000
2  24.285715          64.0000    12.80000         51.20000
3  19.428572          51.2000    10.24000         40.96000
4  14.571428          40.9600     8.19200         32.76800
5   9.714286          32.7680     6.55360         26.21440
6   4.857143          26.2144     5.24288         20.97152

### To test with some layer(s) without PLS, just keep the array empty:

In [3]:
pls_arr = [[34.0000000], [29.1428585], [], [19.4285717], [14.5714283], [9.71428585], [4.85714293]]

llw_pls = 0

for pls in range(len(pls_arr)):
    if pls == 0:
        light_incidence = 100
    else:
        if len(pls_arr[pls]) > 0:
            light_incidence = pls_arr[llw_pls][3]
            llw_pls = pls
        else:
            continue

    light_used = light_incidence * 0.2
    light_available = light_incidence - light_used
    
    pls_arr[pls].append(light_incidence)
    pls_arr[pls].append(light_used)
    pls_arr[pls].append(light_available)

In [4]:
DataFrame(pls_arr, columns = ["pls", "light_incidence", "light_used", "light_available"])

         pls  light_incidence  light_used  light_available
0  34.000000          100.000     20.0000          80.0000
1  29.142858           80.000     16.0000          64.0000
2        NaN              NaN         NaN              NaN
3  19.428572           64.000     12.8000          51.2000
4  14.571428           51.200     10.2400          40.9600
5   9.714286           40.960      8.1920          32.7680
6   4.857143           32.768      6.5536          26.2144

### Testing with two layer without PLS in a row:

In [5]:
pls_arr = [[34.0000000], [29.1428585], [], [], [14.5714283], [9.71428585], [4.85714293]]

llw_pls = 0

for pls in range(len(pls_arr)):
    if pls == 0:
        light_incidence = 100
    else:
        if len(pls_arr[pls]) > 0:
            light_incidence = pls_arr[llw_pls][3]
            llw_pls = pls
        else:
            continue

    light_used = light_incidence * 0.2
    light_available = light_incidence - light_used
    
    pls_arr[pls].append(light_incidence)
    pls_arr[pls].append(light_used)
    pls_arr[pls].append(light_available)

In [6]:
DataFrame(pls_arr, columns = ["pls", "light_incidence", "light_used", "light_available"])

         pls  light_incidence  light_used  light_available
0  34.000000           100.00      20.000           80.000
1  29.142858            80.00      16.000           64.000
2        NaN              NaN         NaN              NaN
3        NaN              NaN         NaN              NaN
4  14.571428            64.00      12.800           51.200
5   9.714286            51.20      10.240           40.960
6   4.857143            40.96       8.192           32.768